services:
  - type: web
    name: pr-ml-inference
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
